# Settings that the LAMMPS build will import when this package library is used

# settings for MLIP on UBUNTU18.04

mlip_INC = -DNDEBUG -fopenmp -std=c++17 -mtune=native -march=native -I/usr/include -Wall -Wextra
mlip_PATH = -L../../lib/mlip

# boost library may be included
mlip_SYSINC =
mlip_SYSLIB = -lgomp
